### ISSUE TITLE
Printf does not work with the evb1000

### ISSUE THREAD

**Issue by ckacl33** [d3s-trento/contiki-uwb#1]
Hi. I've been following your guides to run the rng application on my evb1000 board and I just cannot figure out why the printf fuctions are not working. Below is the compiling message and it does not print out anything at all after make login.

![image](https://user-images.githubusercontent.com/15985444/57614063-56f4f280-75b3-11e9-9a85-2d62ce757ddb.png)

I tried adding "#define PRINTF(...) printf(__VA_ARGS__)" line into rng.c and Makefile but it don't work neither. So I compiled this test-serial project which the code is shown below and apparently it also doesnt work. Seems like serial communication is not working at all although compiling is done successfully. I would really appreciate it if there is any idea you can tell about this situation.

![image](https://user-images.githubusercontent.com/15985444/57614517-6c1e5100-75b4-11e9-9a86-9e83b5908de6.png)

**Comment by pablocorbalan** [comment]
It seems to be just a PORT name issue. Just specify the PORT to connect to as:
```
$ make rng.upload
$ make PORT=/dev/tty.usbmodem1411 login
```
To find the port name simply `$ ls /dev/tty*`. In Ubuntu, the port may be `/dev/ttyUSB0`. Let me know if it works.

**Comment by auberon-lee** [comment]
Hi, I have met the same problem. I am sure the port selection is /dev/ttyUSB0 ( ubuntu os), but it doesn't work. Can you give me some advice? Thank you.

**Comment by auberon-lee** [comment]
This problem has been solved. In current project setting, the printf is output by usb virtual com port, so it should not be connected with uart. I connect the usb port of the evb to the usb port of the host PC, in my Ubuntu system, the port is enumerated as ttyACM0, but not ttyUSB0 or ttyUSB1. Select the ttyACM0 as the PORT, it works well, the print log can be captured.

**Comment by pablocorbalan** [comment]
Hello! Sorry for the late reply. Indeed, you just need to connect the EVB1000 platform USB to your host laptop and then it should work as specified in the instructions.

I will close this issue as USB logging should work fine.
