### ISSUE TITLE
can't find file contiki.h

### ISSUE THREAD

**Issue by li-yizhi** [d3s-trento/contiki-uwb#2]
when i learning your file cir.c. Have error whit the code #include "contiki.h". I could't find this file. Could you please help?

**Comment by tim-ist** [comment]
Hi. Have you cloned the [Contiki](https://github.com/contiki-os/contiki) repo and set the CONTIKI environment variable as described in the [README](https://github.com/d3s-trento/contiki-uwb/blob/master/README.md)?
