### ISSUE TITLE
May I ask about the step after write the ranging example into the DWM1001?

### ISSUE THREAD

**Issue by jordanmsn12** [d3s-trento/contiki-uwb#3]
Hi, 
I am a newcomer on uwb device and contiki system, so it's  a little confuse after  I success compiler the ranging example and write the .hex file to DWM1001, I don't know how to start the next step. Sorry it sound like a stupid question but i can't find the solution. Thanks for helping me.

**Comment by tim-ist** [comment]
Hi, can you copy and paste here several first lines of the serial output of a node after you reset it?

**Comment by jordanmsn12** [comment]
It's full of  "R req R FAIL"'s loop, looks like the picture on the google drive link.
Google drive link: http://bit.ly/2uprKqw


I follow the official document "DWM10001_Gateway_Quick_Deployment_Guide.pdf", 
on J-Flash lite set:
1. Device: NRF52832_XXAA,
2. Interface: SWD
3. Speed: 1000
On Tera Term it set:
1. Serial port speed : 115200

**Comment by jordanmsn12** [comment]
Sorry, rebuild the program with the new file you upload, and get new information.
Here is the output shows on Tera Tern after I push the reset button.
Device1:
DW1000 Radio Configuration:
Channel: 4
PRF: 2
PLEN: 20
PAC Size: 0
TX Pre Code: 17
RX Pre Code: 17
Non-std SFD: 0
Data Rate: 2
PHR Mode: 0
SFD Timeout: 129
Smart TX power: 1
PG Delay: 95
TX Power: 3a5a7a9a
RX ant delay: 16455
TX ant delay: 16455
Short address: 0x16ae
I am 16ae dst 16ae
-----------------------------------
Device2:
Starting Contiki-3.x-3345-g32b5b17
Network stack: Rime over UWB
DW1000 Radio Configuration:
Channel: 4
PRF: 2
PLEN: 20
PAC Size: 0
TX Pre Code: 17
RX Pre Code: 17
Non-std SFD: 0
Data Rate: 2
PHR Mode: 0
SFD Timeout: 129
Smart TX power: 1
PG Delay: 95
TX Power: 3a5a7a9a
RX ant delay: 16455
TX ant delay: 16455
Short address: 0xd41f
I am d41f dst d41f
-------------------------------
My new question is about the short address, should I edit Device1's code, on  'rng.c' ,  linkaddr_t dst = {{0xdd, 0x37}}; to linkaddr_t dst = {{0xd4, 0x1f}}; 
And Device2's code, on 'rng.c', to  linkaddr_t dst = {{0x16, 0xae}};
Or I misunderstand the information. Sorry to bother you, and thanks again!!
![image](https://user-images.githubusercontent.com/5961754/72865169-c9f16400-3d11-11ea-8c5f-b7154386c1dd.png)

**Comment by tim-ist** [comment]
Hi, you should write only one of the addresses to the `dst` and flash both the devices with the same code!

So, write, for example:
```linkaddr_t dst = {{0xd4, 0x1f}}```
 
Flash both the devices and you'll see that device 0x16AE will start ranging with 0xD41F.
Let us know how it goes!

**Comment by tim-ist** [comment]
Did it work? Can I close the issue?

**Comment by jordanmsn12** [comment]
Sorry, because it’s Chinese New Year now, I will try it as soon as possible(Maybe 1/27), and tell you the result!

**Comment by jordanmsn12** [comment]
Thanks, it work!
![success3](https://user-images.githubusercontent.com/5961754/73554620-0a29b280-4487-11ea-8307-c3409bbee93b.JPG)

**Comment by tim-ist** [comment]
Great!
