### ISSUE TITLE
Make Ranging Example Error

### ISSUE THREAD

**Issue by alefelipeoliveira** [d3s-trento/contiki-uwb#4]
Hello, I am trying to compile the ranging example in my machine (Ubuntu 16.04) , but I am facing this issue:

alexandre@alexandre-ThinkPad-T420:~/contiki-uwb/examples/ranging$ make TARGET=dwm1001
SDK: /home/alexandre/Downloads/nRF5_SDK_16.0.0_98a08e2
TODO check if there is an updated script
LINKER_SCRIPT: ../../cpu/nrf52832/ld/nrf52.ld
SOFTDEVICE: 
  CC        ../../cpu/nrf52832/./putchar.c
In file included from /home/alexandre/Downloads/nRF5_SDK_16.0.0_98a08e2/components/libraries/util/app_error.h:54:0,
                 from /home/alexandre/Downloads/nRF5_SDK_16.0.0_98a08e2/components/libraries/util/app_util_platform.h:60,
                 from ../../platform/dwm1001/config/nrfx_glue.h:180,
                 from /home/alexandre/Downloads/nRF5_SDK_16.0.0_98a08e2/modules/nrfx/nrfx.h:46,
                 from /home/alexandre/Downloads/nRF5_SDK_16.0.0_98a08e2/modules/nrfx/hal/nrf_gpio.h:44,
                 from ../../cpu/nrf52832/./dev/../../../platform/dwm1001/platform-conf.h:50,
                 from ../../cpu/nrf52832/./dev/../../../platform/dwm1001/contiki-conf.h:52,
                 from ../../cpu/nrf52832/./dev/uart0.h:46,
                 from ../../cpu/nrf52832/./putchar.c:42:
../../cpu/nrf52832/./putchar.c:45:1: error: expected identifier or '(' before '--' token
 putchar(int c)
 ^
../../contiki/Makefile.include:240: recipe for target 'obj_dwm1001/putchar.o' failed
make: *** [obj_dwm1001/putchar.o] Error 1

I already could finalize MAKE commenting the **#include "contiki-conf.h"** in **uart0.h**, So I tryed to declare the entire route to the file  **#include "../../../platform/dwm1001/contiki-conf.h"** n **uart0.h** but the problem remains.... Could you pls help me to verify this issue?

**Comment by tim-ist** [comment]
Hi, please can you post your compiler version?
```arm-none-eabi-gcc --version```

**Comment by alefelipeoliveira** [comment]
Hi, thanks for the feedback!

Follows my compilar version:

alexandre@alexandre-ThinkPad-T420:~/contiki/contiki-uwb/contiki/tools/cooja$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tim-ist** [comment]
That might be the problem. We use version 9. You can take it from [here](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads).
